### ISSUE TITLE
Boss构想——末路枪手

### ISSUE THREAD

**Issue by AxtonCorporal** [rMuchan/kasumi-challenge#1]
简介：
【末路枪手】以他自己的方式伸张扭曲的正义，他使用一把特制的猎枪，填装的[炼狱之锤]可以击碎最坚固的护甲；猎枪下挂的发射器可以发射[仇恨之链]，束缚住试图顽抗的目标；当发现自己陷入困境之时他会使用早已准备好的[救赎之雾]，使自己化险为夷；当敌人走投无路时，等待他的将是[最终审判]。
基础数据：
看起来像个中年人，实际上也就是个中年人，拥有一般的生命值；
手上的猎枪（三个枪管，外加一个链弹发射器）被他改良了数年之久，拥有较高的攻击力和法术强度；
身着一件曾在某警局工作时的风衣，防御一般，但闪避稍微高一些；
多年的追缉使他充满了决心，拥有较高的生命窃取。
技能：
[十二之焰]：普通攻击，对三个目标造成中等物理伤害。（十二是12号口径的意思）
[炼狱之锤]：发射一颗独头弹，对一个目标造成高额法术伤害，附带持续时间极长的强破甲效果，并在接下来短时间内提高自己的攻击力。
[仇恨之链]：用下挂的发射器发射链弹，对一个目标造成中等法术伤害并吸取一定量的MP，同时大幅度降低该目标的攻击和法强并附加沉默效果。（持续时间应和该技能CD保持一致）
[救赎之雾]：释放烟雾弹（实际上是像烟雾的法术介质），净化自己后给自己一个较高的护盾，并在接下来短时间内提高自身的闪避率。
[最终审判]：终极技能，将猎枪顶在敌人脑门上后全弹发射，该回合内大幅提升生命窃取和暴击倍率，对一个目标造成三次分开判定的高额物理伤害。
构想：
除了普通攻击外的其他攻击均为单体攻击，考验玩家的单体恢复/护盾能力；
[仇恨之链]可理解为持续时间内中招的玩家跟瘫了差不多；
[炼狱之锤]附带的长时强破甲效果使得普攻对玩家而言也具有危险性，但更多的则是配合大招[最终审判]，理论上同级下被强破甲时吃满大招伤害必定去世；
[救赎之雾]一定程度上弥补了其防御较弱的缺点，同时其净化效果也能克制降攻打法。

**Comment by IceZero610** [comment]
[仇恨之链]这个技能设计得并不好，效果繁杂的同时也会给点到名的玩家带来巨大的挫败感。
目前游戏系统希望严格区分物理与魔法，规定只有普通攻击会造成物理伤害，所以[最终审判]是不能实现的。
不过【末路枪手】颇有一种西部牛仔加上一点暴徒的色彩，角色形象我还是蛮喜欢的。
