### ISSUE TITLE
加防技能表现不如加盾技能突出

### ISSUE THREAD

**Issue by scarletwar** [rMuchan/kasumi-challenge#3]
主要表现在boss的大招和小技能都是法伤，加防既不能阻止boss回血也不能阻止boss高伤大招。而且有减防技能的boss即使是你加了防御一样几乎全减(指同等级范围boss）。可以考虑把忍者之类的大招伤害改成比较合理的高物理伤害？比如锁喉3000面板伤害在5点防御的时候就会是600伤害了（不过好像如果有盾的情况下伤害全按没有防御去计算的？这样可能会出事）

**Comment by IceZero610** [comment]
设计上就希望物理伤害只会由普通攻击造成，而所有技能造成的都是魔法伤害，希望这样可以把物理和魔法的来源区分开，而不是将其变为简单的两种伤害类型。所以技能上就不要考虑物理高伤什么的了(
护盾的引入其实就是为了和直接回血所区别开——由于护盾不计算防御，所以在攻击角色时效果并不好的物理攻击在破盾的效率反而高于真实伤害的魔法攻击。
——以上是我的一点设计的想法。
不过加防御的表现确实有点不尽人意，特别是在高等级高增益幅度有减甲技能的Boss手下这个技能意义就更小了。

目前已经有修改护甲计算公式的打算，另外也在设计一些其他的技能效果来加强防御手段。请期待
