### ISSUE TITLE
忍者boss似乎有点过于强大了

### ISSUE THREAD

**Issue by scarletwar** [rMuchan/kasumi-challenge#4]
忍者boss闪避高，前期生存强力，小技能有加1000+的盾也提升了不少生存能力。而且忍者有30回合的爆伤buff，早期若不能刀刀烈火（并且命中）buff叠起来之后就打不过了。

**Comment by IceZero610** [comment]
游戏发布初期，物理构筑在暴击的加成下非常可怕，设计忍者的目的是为了引导玩家尝试法术构筑。
而如今忍者的意义依旧如此，玩家需要一个了解“净化”和“魔法”概念的途径，忍者便是这个重要的途径。
忍者拥有极其高额的护盾，这意味着玩家同样需要物理伤害来破盾。这也对玩家队伍的组成有了一定的要求。
总的来说这个Boss的表现还是比较令人满意的，未来可能会对其的数值做一些轻微调整。
